apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-service
  template:
    metadata:
      labels:
        app: bot-service
    spec:
      containers:
        - name: bot-service
          image: anhnguyenduc3/othellobotservice:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8889
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot-service
  ports:
    - port: 8889
      targetPort: 8889
      nodePort: 30085
  type: NodePort
